version: '3'
services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: AcMkuyYei1*d    # 在这里输入你要设置的mysql密码
       MYSQL_DATABASE: wordpress
       MYSQL_USER: pengpeng
       MYSQL_PASSWORD: whpAcMkuyYei1*d123
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
        - wp_site:/var/www/html     # 定义卷后，compose down之类的操作不会导致你的文章等数据丢失
     expose:
       - 80
     restart: always
     environment:
       VIRTUAL_HOST: 47.105.74.81
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: pengpeng
       WORDPRESS_DB_PASSWORD: whpAcMkuyYei1*d123
   nginx-proxy:
     image: jwilder/nginx-proxy
     container_name: nginx-proxy
     restart: always
     ports:
       - "80:80"
       - "443:443"
     volumes:
       - /var/run/docker.sock:/tmp/docker.sock:ro   # docker.sock是docker守护进程默认监听的Unix域套接字，容器进程通过它与守护进程进行通信。以后添加新的站点时，nginx将会自动发现并重启服务
       - nginx_certs:/etc/nginx/certs:ro    # nginx的证书目录，:ro指定为只读
volumes:
    db_data:
    wp_site:
    nginx_certs:
networks:
   default:
     external:
       name: nginx-proxy